define competitor = Character("Ava", color="#ee4b2b", image="competitor")
define company = Character("Company", color="#e5e4e2")
define friend = Character("Riley", color="#e4d00a", image="friend")
define mentor = Character("Jasper", color="#9fe2bf", image="mentor")
define player = Character("[player_name]", color="#c8c8ff")
define supplier = Character("Supplier", color="#e5e4e2")
